local_backend: true     # enable local file writes
backend:
  name: git-gateway     # still needed to drive proxy-server

media_folder: "public/uploads"          # where uploaded files go (inside the repo)
public_folder: "/uploads"               # how they're referenced in the site

publish_mode: editorial_workflow        # optional: enables drafts + PR review

collections:
  - name: "pages"
    label: "Pages"
    label_singular: "Page"
    folder: "content/pages"
    create: true
    slug: "{{slug}}"
    format: "frontmatter"
    extension: "md"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "blog"
    label: "Blog Posts"
    folder: "content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    format: "frontmatter"
    extension: "md"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Excerpt", name: "excerpt", widget: "text", required: false }
      - { label: "Cover Image", name: "cover", widget: "image", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: menus
    label: Menus
    folder: data/menus
    extension: json
    format: json
    fields:
      - label: Items
        name: items
        widget: list
        fields:
          - { label: Label, name: label, widget: string }
          - { label: URL, name: url, widget: string }
  - name: "startseite"
    label: "Startseite"
    files:
      - label: "Startseite Inhalt"
        name: "home"
        file: "content/startseite.md"
        fields:
          - { label: "Seitentitel", name: "title", widget: "string" }

          - label: "Hero Bereich"
            name: "hero"
            widget: "object"
            fields:
              - { label: "Überschrift", name: "heading", widget: "string" }
              - { label: "Subtext1", name: "subtext1", widget: "text" }
              - { label: "Subtext 2", name: "subtext2", widget: "text" }
              - { label: "Subtext 3", name: "subtext3", widget: "text" }
              - { label: "Hintergrundbild", name: "background", widget: "image" }

          - label: "Leistungen (Cards)"
            name: "cards"
            widget: "list"
            fields:
              - { label: "Titel", name: "title", widget: "string" }
              - { label: "Beschreibung", name: "description", widget: "text" }
              - { label: "Button Text", name: "button", widget: "string" }
              - { label: "Button Link", name: "link", widget: "string" }

          - label: "Filterarten (Icons)"
            name: "services"
            widget: "object"
            fields:
              - label: "Überschrift"
                name: "heading"
                widget: "string"
                required: false
                default: ""

              - label: "Filterarten (Liste)"
                name: "items"
                widget: "list"
                fields:
                  - { label: "Name", name: "name", widget: "string" }
                  - { label: "Bild", name: "icon", widget: "image" }

          - label: "FAQ Accordion"
            name: "faq"
            widget: "list"
            fields:
              - { label: "Frage", name: "question", widget: "string" }
              - { label: "Antwort", name: "answer", widget: "markdown", rich_text: true, required: false, default: "" }

          - label: "Accordion Image"
            name: "accordion_image"
            widget: "image"

          - label: "Team Bilder"
            name: "team"
            widget: "list"
            fields:
              - label: "Typ"
                name: "media_type"
                widget: "select"
                options: ["image", "video"]
                default: "image"

              - label: "Bild"
                name: "image"
                widget: "image"
                required: false
                hint: "Wird nur verwendet, wenn Typ 'image' ist"

              - label: "Video"
                name: "video"
                widget: "file"
                required: false
                hint: "Wird nur verwendet, wenn Typ 'video' ist"

          - label: "Standort Karte"
            name: "map_embed"
            widget: "text"
            hint: "HTML Embed-Code für Karte einfügen"

          - label: "Über Greencar"
            name: "about"
            widget: "markdown"
            rich_text: true
            required: false
            default: ""

          - label: "Footer"
            name: "footer"
            widget: "list"
            fields:
              - { label: "Logo", name: "logo", widget: "image" }
              - { label: "Link URL", name: "url", widget: "string" }

          - label: "Hero Bereich Beispiel"
            name: "hero_example"
            widget: "object"
            fields:
              - { label: "Überschrift", name: "heading", widget: "string", required: false }
              - label: "Subtexte"
                name: "subtexts"
                widget: "list"
                field: { label: "Textzeile", name: "text", widget: "string" }
              - { label: "Hintergrundbild", name: "background", widget: "image", required: false  }
