local_backend: true     # enable local file writes
backend:
  name: git-gateway     # still needed to drive proxy-server

media_folder: "public/uploads"          # where uploaded files go (inside the repo)
public_folder: "/uploads"               # how they're referenced in the site

publish_mode: editorial_workflow        # optional: enables drafts + PR review

collections:
  - name: "pages"
    label: "Pages"
    label_singular: "Page"
    folder: "content/pages"
    create: true
    slug: "{{slug}}"
    format: "frontmatter"
    extension: "md"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "blog"
    label: "Blog Posts"
    folder: "content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    format: "frontmatter"
    extension: "md"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Excerpt", name: "excerpt", widget: "text", required: false }
      - { label: "Cover Image", name: "cover", widget: "image", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: menus
    label: Menus
    folder: data/menus
    extension: json
    format: json
    fields:
      - label: Items
        name: items
        widget: list
        fields:
          - { label: Label, name: label, widget: string }
          - { label: URL, name: url, widget: string }
  - name: "startseite"
    label: "Startseite"
    files:
      - label: "Startseite Inhalt"
        name: "home"
        file: "content/startseite.md"
        fields:
          - { label: "Seitentitel", name: "title", widget: "string" }

          - label: "Hero Bereich"
            name: "hero"
            widget: "object"
            fields:
              - { label: "Überschrift", name: "heading", widget: "string" }
              - { label: "Subtext1", name: "subtext1", widget: "text" }
              - { label: "Subtext 2", name: "subtext2", widget: "text" }
              - { label: "Subtext 3", name: "subtext3", widget: "text" }
              - { label: "Hintergrundbild", name: "background", widget: "image" }

          - label: "Leistungen (Cards)"
            name: "cards"
            widget: "list"
            fields:
              - { label: "Titel", name: "title", widget: "string" }
              - { label: "Beschreibung", name: "description", widget: "text" }
              - { label: "Button Text", name: "button", widget: "string" }
              - { label: "Button Link", name: "link", widget: "string" }

          - label: "Filterarten (Icons)"
            name: "services"
            widget: "list"
            fields:
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Bild", name: "icon", widget: "image" }

          - label: "FAQ Accordion"
            name: "faq"
            widget: "list"
            fields:
              - { label: "Frage", name: "question", widget: "string" }
              - { label: "Antwort", name: "answer", widget: "markdown" }

          - label: "Team Bilder"
            name: "team"
            widget: "list"
            fields:
              - { label: "Bild", name: "image", widget: "image" }
              - { label: "Alt Text", name: "alt", widget: "string" }

          - label: "Standort Karte"
            name: "map_embed"
            widget: "text"
            hint: "HTML Embed-Code für Karte einfügen"

          - label: "Über Greencar"
            name: "about"
            widget: "markdown"
